import type { Metadata } from "next";
import { appInfo } from "@/appInfo";

export const metadata: Metadata = {
  title: `Book Appointment with ${appInfo.name}`,
  description: "Generated by create next app",
};
